# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Provability-Fabric Contributors

version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: provability_fabric
      POSTGRES_USER: pf_user
      POSTGRES_PASSWORD: pf_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ledger:
    build: .
    environment:
      DATABASE_URL: postgresql://pf_user:pf_password@postgres:5432/provability_fabric
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ledger
    deploy:
      replicas: 1

volumes:
  postgres_data:
