[build]
# Enable parallel compilation
jobs = 0

[target.x86_64-unknown-linux-gnu]
# Enable CPU-specific optimizations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+sse4.2,+avx2,+fma",
    "-C", "link-arg=-Wl,--strip-all",
]

[target.aarch64-unknown-linux-gnu]
# ARM64 optimizations
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+fp-armv8,+crypto,+neon",
    "-C", "link-arg=-Wl,--strip-all",
]

[lints.rust]
# Forbid unsafe code
unsafe_code = "forbid"
# Additional safety checks
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_imports = "warn"
unused_must_use = "warn"
unused_qualifications = "warn"
unused_results = "warn"
unused_unsafe = "warn"
unused_variables = "warn"

[lints.clippy]
# Enable all Clippy lints
all = "warn"
# Pedantic lints for maximum code quality
pedantic = "warn"
# Performance-focused lints
perf = "warn"
# Correctness lints
correctness = "warn"
# Style lints
style = "warn"
# Complexity lints
complexity = "warn"
# Suspicious lints
suspicious = "warn"
# Nursery lints (experimental)
nursery = "warn"

# Specific performance lints
cast_lossless = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
default_numeric_fallback = "warn"
explicit_iter_loop = "warn"
explicit_into_iter_loop = "warn"
float_cmp = "warn"
if_not_else = "warn"
inefficient_to_string = "warn"
let_underscore_lock = "warn"
map_unwrap_or = "warn"
match_as_ref = "warn"
maybe_infinite_iter = "warn"
mem_replace_with_default = "warn"
needless_borrow = "warn"
needless_loop = "warn"
needless_pass_by_value = "warn"
option_map_unit_fn = "warn"
path_buf_push_overwrite = "warn"
range_plus_one = "warn"
range_minus_one = "warn"
redundant_closure = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
redundant_pattern_matching = "warn"
redundant_slicing = "warn"
redundant_static_lifetimes = "warn"
same_functions_in_if_blocks = "warn"
semicolon_if_nothing_returned = "warn"
single_char_pattern = "warn"
string_lit_as_bytes = "warn"
string_to_string = "warn"
type_complexity = "warn"
unnecessary_cast = "warn"
unnecessary_filter_map = "warn"
unnecessary_fold = "warn"
unnecessary_mut_passed = "warn"
unnecessary_sort_by = "warn"
unnecessary_unwrap = "warn"
unused_async = "warn"
unused_self = "warn"
use_self = "warn"
verbose_file_reads = "warn"
zero_prefixed_literal = "warn"

[profile.release]
# Profile-guided optimization
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false

[profile.dev]
# Development optimizations
opt-level = 1
debug = true
overflow-checks = true
