apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admission.fullname" . }}
  labels:
    {{- include "admission.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "admission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "admission.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "admission.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: PORT
              value: "8443"
            - name: CERT_FILE
              value: "/etc/certs/tls.crt"
            - name: KEY_FILE
              value: "/etc/certs/tls.key"
            - name: LEANCHECK_URL
              value: {{ .Values.leancheck.url | quote }}
            - name: ENABLE_POLICY
              value: {{ .Values.enablePolicy | default "true" | quote }}
            - name: LEDGER_URL
              value: {{ .Values.ledger.url | default "http://ledger:4000/graphql" | quote }}
          volumeMounts:
            - name: certs
              mountPath: /etc/certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
      volumes:
        - name: certs
          secret:
            secretName: {{ include "admission.fullname" . }}-certs 