# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Provability-Fabric Contributors

site_name: Provability-Fabric
site_description: Open-source framework for AI agent behavioral guarantees
site_author: Provability-Fabric Contributors
site_url: https://provability-fabric.org

repo_name: provability-fabric/provability-fabric
repo_url: https://github.com/provability-fabric/provability-fabric
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slug_github_compat: true
      tabs_style: material
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  
  # PF-CORE Implementation
  - PF-CORE Status: pf-core-status.md
  
  # Core Components
  - Spec Bundles: spec-bundles.md
  - Lean Proofs: lean.md
  - Runtime: runtime.md
  
  # Security & Attestation
  - Security Overview: security/overview.md
  - Decision Path: img/decision_path.svg
  - Attestation Service: runtime/attestor/README.md
  
  # Client SDKs
  - SDKs Overview: core/sdk/README.md
  - TypeScript SDK: core/sdk/typescript/README.md
  - Go SDK: core/sdk/go/README.md
  - Rust SDK: core/sdk/rust/README.md
  
  # Performance & Optimization
  - Performance Benchmarks: bench/README.md
  - WASM Worker Pool: runtime/wasm-sandbox/README.md
  - Batch Crypto: core/crypto/README.md
  
  # CI/CD & Testing
  - Cross-repo Testing: .github/workflows/release.yaml
  - Release Pipeline: .github/workflows/README.md
  
  # Generated Specs
  - Generated Specs: generated/*.md
  
  # API Reference
  - API Reference: api.md
  
  # Development
  - Contributing: contributing.md
  - Development Guide: dev/README.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/provability-fabric/provability-fabric
    - icon: fontawesome/brands/discord
      link: https://discord.gg/provability-fabric
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/provabilityfab

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 