# SPDX-License-Identifier: Apache-2.0
# Copyright 2025 Provability-Fabric Contributors

name: Performance Tests

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  performance:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build sidecar watcher
        run: |
          cd runtime/sidecar-watcher
          cargo build --release

      - name: Run performance benchmark
        run: |
          python scripts/bench.py --count 100000 --output perf-results.json

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: perf-results-${{ github.run_number }}
          path: perf-results.json

      - name: Deploy to gh-pages
        if: github.event_name == 'schedule'
        run: |
          # Install gh-pages
          npm install -g gh-pages

          # Create perf directory
          mkdir -p perf

          # Copy results with timestamp
          cp perf-results.json perf/$(date +%Y-%m-%d).json

          # Deploy to gh-pages branch
          gh-pages --dist perf --add
