name: Cross-Repo PF CI Consumer

on:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  pf-ci:
    uses: org/ci-workflows/.github/workflows/pf-ci.yaml@v1
    with:
      pr_number: ${{ github.event.pull_request.number || '' }}
      run_phases: "2,3,6"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
