name: APOLLO Proof Bot

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: "0 2 * * *"
  issue_comment:
    # Trigger on "/prove" comment
    types: [created]
  workflow_dispatch:
    # Manual trigger

jobs:
  proof-bot:
    runs-on: ubuntu-latest

    # Only run on main branch or when triggered by comment
    if: github.ref == 'refs/heads/main' || github.event_name == 'issue_comment'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Full history for git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd tools/proofbot
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "APOLLO Proof Bot"
          git config --global user.email "proofbot@provability-fabric.local"

      - name: Run APOLLO Proof Bot
        id: proofbot
        run: |
          cd tools/proofbot
          python run.py --api-url ${{ vars.APOLLO_API_URL || 'http://localhost:8080' }}
        continue-on-error: true

      - name: Create Pull Request
        if: steps.proofbot.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-proof: Resolve admits via APOLLO"
          title: "🤖 Auto-proof: Resolve admits via APOLLO"
          body: |
            This PR was automatically generated by the APOLLO Proof Bot.

            ## Changes
            - Resolved `sorry` and `by admit` statements in Lean proofs
            - Applied proof patches generated by APOLLO API

            ## Review Required
            This PR requires manual review by a CODEOWNER before merging.

            /cc @${{ github.repository_owner }}/codeowners
          branch: auto-proof/${{ github.run_id }}
          delete-branch: true
          labels: |
            auto-proof
            enhancement
          assignees: ${{ github.repository_owner }}

      - name: Comment on Issue
        if: github.event_name == 'issue_comment' && steps.proofbot.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes('Auto-proof: Resolve admits via APOLLO')
            );

            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `✅ APOLLO Proof Bot has processed the repository and created a pull request to resolve admits.`
              });
            }

      - name: Comment on Issue (No Changes)
        if: github.event_name == 'issue_comment' && steps.proofbot.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `ℹ️ APOLLO Proof Bot found no admits to resolve or encountered an error. Check the workflow logs for details.`
            });
