name: Standards Pin Drift Check

on:
  push:
    branches: [main, develop]
    paths:
      - "external/**"
      - "tools/standards/**"
      - ".github/workflows/standards-pin.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "external/**"
      - "tools/standards/**"
      - ".github/workflows/standards-pin.yml"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodules
        run: make submodules

      - name: Standards pin check
        run: make standards-pin-check

      - name: Comment on PR (drift)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Standards pin drift detected. Ensure submodules are checked out at tags in tools/standards/versions.json.'
            })
